# Generated by Django 5.0.6 on 2024-05-21 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='analysis/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=255)),
                ('treatment_start_date', models.DateField(auto_now_add=True)),
                ('follow_up_dates', models.TextField(blank=True)),
                ('recovery_date', models.DateField(blank=True, null=True)),
                ('analysis_images', models.ManyToManyField(blank=True, to='Add_Data.analysis_image')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='prescriptions/%Y/%m/%d/')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Add_Data.medical_record')),
            ],
        ),
        migrations.AddField(
            model_name='medical_record',
            name='prescription_images',
            field=models.ManyToManyField(blank=True, related_name='medical_records', to='Add_Data.prescription_image'),
        ),
    ]
