# Generated by Django 5.0.6 on 2024-05-23 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_record',
            name='analysis_images',
        ),
        migrations.RemoveField(
            model_name='medical_record',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='medical_record',
            name='prescription_images',
        ),
        migrations.RemoveField(
            model_name='prescription_image',
            name='medical_record',
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('prescription_images', models.ImageField(blank=True, upload_to='prescriptions/%Y/%m/%d/')),
                ('test_images', models.ImageField(blank=True, upload_to='tests/%Y/%m/%d/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Analysis_Image',
        ),
        migrations.DeleteModel(
            name='Medical_Record',
        ),
        migrations.DeleteModel(
            name='Prescription_Image',
        ),
    ]
