# Generated by Django 5.0.6 on 2024-05-24 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Data', '0003_rename_name_disease_disease_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='analysis_images',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='prescription_images',
        ),
        migrations.CreateModel(
            name='AnalysisImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='analysis/%Y/%m/%d/')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_images', to='Add_Data.disease')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prescriptions/%Y/%m/%d/')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_images', to='Add_Data.disease')),
            ],
        ),
    ]
