# Generated by Django 5.0.6 on 2024-06-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Data', '0004_remove_disease_analysis_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='recovery_date',
            field=models.DateField(null=True),
        ),
    ]
