# Generated by Django 5.0.6 on 2024-06-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Data', '0005_alter_disease_recovery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='modified_dates',
            field=models.TextField(null=True),
        ),
    ]
